### ISSUE TITLE
Passwords?

### ISSUE THREAD

**Issue by kinomakino** [mbrg/zapcreds#1]
Just to confirm, it doesn't show the credentials (passwords), just the owner, right?

Thanks for the work and the chat.

**Comment by mbrg** [comment]
Hi! This project hasn't been updated for a while now :). We've focused efforts on https://github.com/mbrg/power-pwn that can find the actual creds.

Zapier connections won't give the actual creds. But you can use the connection object to perform API calls using those credentials.
